name = "cleantype"
license = "MIT"
licenselink = "https://github.com/zmarcantel/hugo-cleantype/blob/master/LICENSE.md"
description = ""
homepage = "https://zmar.me"
tags = []
features = []
min_version = 0.18

[author]
  name = "Zach Marcantel <zmarcantel@gmail.com>"
  homepage = "https://zmar.me"
